/*----- PROTECTED REGION ID(BaslerCameraStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        BaslerCameraStateMachine.cpp
//
// description : State machine file for the BaslerCamera class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <BaslerCamera.h>

/*----- PROTECTED REGION END -----*/	//	BaslerCamera::BaslerCameraStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace BaslerCamera_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_ExposureTime_allowed()
 *	Description : Execution allowed for ExposureTime attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_ExposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(BaslerCamera::ExposureTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::ExposureTimeStateAllowed_WRITE

	//	Not any excluded states for ExposureTime attribute in read access.
	/*----- PROTECTED REGION ID(BaslerCamera::ExposureTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::ExposureTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_FrameRate_allowed()
 *	Description : Execution allowed for FrameRate attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_FrameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FrameRate attribute in Write access.
	/*----- PROTECTED REGION ID(BaslerCamera::FrameRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::FrameRateStateAllowed_WRITE

	//	Not any excluded states for FrameRate attribute in read access.
	/*----- PROTECTED REGION ID(BaslerCamera::FrameRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::FrameRateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(BaslerCamera::GainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(BaslerCamera::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_TriggerMode_allowed()
 *	Description : Execution allowed for TriggerMode attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_TriggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TriggerMode attribute in Write access.
	/*----- PROTECTED REGION ID(BaslerCamera::TriggerModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::TriggerModeStateAllowed_WRITE

	//	Not any excluded states for TriggerMode attribute in read access.
	/*----- PROTECTED REGION ID(BaslerCamera::TriggerModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::TriggerModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_BeamProfileImg_allowed()
 *	Description : Execution allowed for BeamProfileImg attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_BeamProfileImg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for BeamProfileImg attribute in read access.
	/*----- PROTECTED REGION ID(BaslerCamera::BeamProfileImgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::BeamProfileImgStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_GrabImage_allowed()
 *	Description : Execution allowed for GrabImage attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_GrabImage_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GrabImage command.
	/*----- PROTECTED REGION ID(BaslerCamera::GrabImageStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::GrabImageStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : BaslerCamera::is_ConnectCamera_allowed()
 *	Description : Execution allowed for ConnectCamera attribute
 */
//--------------------------------------------------------
bool BaslerCamera::is_ConnectCamera_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ConnectCamera command.
	/*----- PROTECTED REGION ID(BaslerCamera::ConnectCameraStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	BaslerCamera::ConnectCameraStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(BaslerCamera::BaslerCameraStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	BaslerCamera::BaslerCameraStateAllowed.AdditionalMethods

}	//	End of namespace
