/*----- PROTECTED REGION ID(DeviceBClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceBClass.cpp
//
// description : C++ source for the DeviceBClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the DeviceB once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DeviceBClass.h>

/*----- PROTECTED REGION END -----*/	//	DeviceBClass.cpp

//-------------------------------------------------------------------
/**
 *	Create DeviceBClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_DeviceB_class(const char *name) {
		return DeviceB_ns::DeviceBClass::init(name);
	}
}

namespace DeviceB_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
DeviceBClass *DeviceBClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		DeviceBClass::DeviceBClass(string &s)
 * description : 	constructor for the DeviceBClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
DeviceBClass::DeviceBClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering DeviceBClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(DeviceBClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::constructor

	cout2 << "Leaving DeviceBClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		DeviceBClass::~DeviceBClass()
 * description : 	destructor for the DeviceBClass
 */
//--------------------------------------------------------
DeviceBClass::~DeviceBClass()
{
	/*----- PROTECTED REGION ID(DeviceBClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		DeviceBClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
DeviceBClass *DeviceBClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new DeviceBClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		DeviceBClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
DeviceBClass *DeviceBClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		MeasureTempClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *MeasureTempClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "MeasureTempClass::execute(): arrived" << endl;
	((static_cast<DeviceB *>(device))->measure_temp());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum DeviceBClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum DeviceBClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum DeviceBClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void DeviceBClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void DeviceBClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void DeviceBClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(DeviceBClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new DeviceB(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		DeviceB *dev = static_cast<DeviceB *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(DeviceBClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void DeviceBClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(DeviceBClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::attribute_factory_before
	//	Attribute : Temperature_B1
	Temperature_B1Attrib	*temperature_b1 = new Temperature_B1Attrib();
	Tango::UserDefaultAttrProp	temperature_b1_prop;
	//	description	not set for Temperature_B1
	//	label	not set for Temperature_B1
	//	unit	not set for Temperature_B1
	//	standard_unit	not set for Temperature_B1
	//	display_unit	not set for Temperature_B1
	//	format	not set for Temperature_B1
	//	max_value	not set for Temperature_B1
	//	min_value	not set for Temperature_B1
	//	max_alarm	not set for Temperature_B1
	//	min_alarm	not set for Temperature_B1
	//	max_warning	not set for Temperature_B1
	//	min_warning	not set for Temperature_B1
	//	delta_t	not set for Temperature_B1
	//	delta_val	not set for Temperature_B1
	
	temperature_b1->set_default_properties(temperature_b1_prop);
	//	Not Polled
	temperature_b1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(temperature_b1);

	//	Attribute : Temperature_B2
	Temperature_B2Attrib	*temperature_b2 = new Temperature_B2Attrib();
	Tango::UserDefaultAttrProp	temperature_b2_prop;
	//	description	not set for Temperature_B2
	//	label	not set for Temperature_B2
	//	unit	not set for Temperature_B2
	//	standard_unit	not set for Temperature_B2
	//	display_unit	not set for Temperature_B2
	//	format	not set for Temperature_B2
	//	max_value	not set for Temperature_B2
	//	min_value	not set for Temperature_B2
	//	max_alarm	not set for Temperature_B2
	//	min_alarm	not set for Temperature_B2
	//	max_warning	not set for Temperature_B2
	//	min_warning	not set for Temperature_B2
	//	delta_t	not set for Temperature_B2
	//	delta_val	not set for Temperature_B2
	
	temperature_b2->set_default_properties(temperature_b2_prop);
	//	Not Polled
	temperature_b2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(temperature_b2);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(DeviceBClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void DeviceBClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(DeviceBClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::pipe_factory_before
	/*----- PROTECTED REGION ID(DeviceBClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void DeviceBClass::command_factory()
{
	/*----- PROTECTED REGION ID(DeviceBClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::command_factory_before


	//	Command MeasureTemp
	MeasureTempClass	*pMeasureTempCmd =
		new MeasureTempClass("MeasureTemp",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pMeasureTempCmd);

	/*----- PROTECTED REGION ID(DeviceBClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		DeviceBClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void DeviceBClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(DeviceBClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		DeviceBClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void DeviceBClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		DeviceB *dev = static_cast<DeviceB *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(DeviceBClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceBClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : DeviceBClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *DeviceBClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(DeviceBClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	DeviceBClass::Additional Methods
} //	namespace
