/*----- PROTECTED REGION ID(DeviceB.h) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceB.h
//
// description : Include file for the DeviceB class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DeviceB_H
#define DeviceB_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	DeviceB.h

/**
 *  DeviceB class description:
 *    
 */

namespace DeviceB_ns
{
/*----- PROTECTED REGION ID(DeviceB::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	DeviceB::Additional Class Declarations

class DeviceB : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(DeviceB::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	DeviceB::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_Temperature_B1_read;
	Tango::DevDouble	*attr_Temperature_B2_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DeviceB(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DeviceB(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	DeviceB(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~DeviceB() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : DeviceB::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Temperature_B1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Temperature_B1(Tango::Attribute &attr);
	virtual bool is_Temperature_B1_allowed(Tango::AttReqType type);
/**
 *	Attribute Temperature_B2 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Temperature_B2(Tango::Attribute &attr);
	virtual bool is_Temperature_B2_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : DeviceB::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command MeasureTemp related method
	 *	Description: 
	 *
	 */
	virtual void measure_temp();
	virtual bool is_MeasureTemp_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : DeviceB::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(DeviceB::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	DeviceB::Additional Method prototypes
};

/*----- PROTECTED REGION ID(DeviceB::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	DeviceB::Additional Classes Definitions

}	//	End of namespace

#endif   //	DeviceB_H
