/*----- PROTECTED REGION ID(DeviceBStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceBStateMachine.cpp
//
// description : State machine file for the DeviceB class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <DeviceB.h>

/*----- PROTECTED REGION END -----*/	//	DeviceB::DeviceBStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace DeviceB_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : DeviceB::is_Temperature_B1_allowed()
 *	Description : Execution allowed for Temperature_B1 attribute
 */
//--------------------------------------------------------
bool DeviceB::is_Temperature_B1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Temperature_B1 attribute in read access.
	/*----- PROTECTED REGION ID(DeviceB::Temperature_B1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceB::Temperature_B1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : DeviceB::is_Temperature_B2_allowed()
 *	Description : Execution allowed for Temperature_B2 attribute
 */
//--------------------------------------------------------
bool DeviceB::is_Temperature_B2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Temperature_B2 attribute in read access.
	/*----- PROTECTED REGION ID(DeviceB::Temperature_B2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceB::Temperature_B2StateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : DeviceB::is_MeasureTemp_allowed()
 *	Description : Execution allowed for MeasureTemp attribute
 */
//--------------------------------------------------------
bool DeviceB::is_MeasureTemp_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MeasureTemp command.
	/*----- PROTECTED REGION ID(DeviceB::MeasureTempStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceB::MeasureTempStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(DeviceB::DeviceBStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	DeviceB::DeviceBStateAllowed.AdditionalMethods

}	//	End of namespace
