/*----- PROTECTED REGION ID(CameraStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        CameraStateMachine.cpp
//
// description : State machine file for the Camera class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Camera.h>

/*----- PROTECTED REGION END -----*/	//	Camera::CameraStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Camera_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Camera::is_exposureTime_allowed()
 *	Description : Execution allowed for exposureTime attribute
 */
//--------------------------------------------------------
bool Camera::is_exposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(Camera::exposureTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::exposureTimeStateAllowed_WRITE

	//	Not any excluded states for exposureTime attribute in read access.
	/*----- PROTECTED REGION ID(Camera::exposureTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::exposureTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Camera::is_frameRate_allowed()
 *	Description : Execution allowed for frameRate attribute
 */
//--------------------------------------------------------
bool Camera::is_frameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frameRate attribute in Write access.
	/*----- PROTECTED REGION ID(Camera::frameRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::frameRateStateAllowed_WRITE

	//	Not any excluded states for frameRate attribute in read access.
	/*----- PROTECTED REGION ID(Camera::frameRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::frameRateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Camera::is_triggerMode_allowed()
 *	Description : Execution allowed for triggerMode attribute
 */
//--------------------------------------------------------
bool Camera::is_triggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for triggerMode attribute in Write access.
	/*----- PROTECTED REGION ID(Camera::triggerModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::triggerModeStateAllowed_WRITE

	//	Not any excluded states for triggerMode attribute in read access.
	/*----- PROTECTED REGION ID(Camera::triggerModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::triggerModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Camera::is_beamProfileImg_allowed()
 *	Description : Execution allowed for beamProfileImg attribute
 */
//--------------------------------------------------------
bool Camera::is_beamProfileImg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for beamProfileImg attribute in read access.
	/*----- PROTECTED REGION ID(Camera::beamProfileImgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::beamProfileImgStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Camera::is_GrabImage_allowed()
 *	Description : Execution allowed for GrabImage attribute
 */
//--------------------------------------------------------
bool Camera::is_GrabImage_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GrabImage command.
	/*----- PROTECTED REGION ID(Camera::GrabImageStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Camera::GrabImageStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Camera::CameraStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Camera::CameraStateAllowed.AdditionalMethods

}	//	End of namespace
