/*----- PROTECTED REGION ID(DeviceAStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceAStateMachine.cpp
//
// description : State machine file for the DeviceA class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <DeviceA.h>

/*----- PROTECTED REGION END -----*/	//	DeviceA::DeviceAStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace DeviceA_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : DeviceA::is_TestAttribute_A1_allowed()
 *	Description : Execution allowed for TestAttribute_A1 attribute
 */
//--------------------------------------------------------
bool DeviceA::is_TestAttribute_A1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TestAttribute_A1 attribute in Write access.
	/*----- PROTECTED REGION ID(DeviceA::TestAttribute_A1StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::TestAttribute_A1StateAllowed_WRITE

	//	Not any excluded states for TestAttribute_A1 attribute in read access.
	/*----- PROTECTED REGION ID(DeviceA::TestAttribute_A1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::TestAttribute_A1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : DeviceA::is_TestAttribute_A2_allowed()
 *	Description : Execution allowed for TestAttribute_A2 attribute
 */
//--------------------------------------------------------
bool DeviceA::is_TestAttribute_A2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TestAttribute_A2 attribute in Write access.
	/*----- PROTECTED REGION ID(DeviceA::TestAttribute_A2StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::TestAttribute_A2StateAllowed_WRITE

	//	Not any excluded states for TestAttribute_A2 attribute in read access.
	/*----- PROTECTED REGION ID(DeviceA::TestAttribute_A2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::TestAttribute_A2StateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : DeviceA::is_GrabImage_allowed()
 *	Description : Execution allowed for GrabImage attribute
 */
//--------------------------------------------------------
bool DeviceA::is_GrabImage_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GrabImage command.
	/*----- PROTECTED REGION ID(DeviceA::GrabImageStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::GrabImageStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(DeviceA::DeviceAStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	DeviceA::DeviceAStateAllowed.AdditionalMethods

}	//	End of namespace
