/*----- PROTECTED REGION ID(DeviceA.h) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceA.h
//
// description : Include file for the DeviceA class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DeviceA_H
#define DeviceA_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	DeviceA.h

/**
 *  DeviceA class description:
 *    
 */

namespace DeviceA_ns
{
/*----- PROTECTED REGION ID(DeviceA::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	DeviceA::Additional Class Declarations

class DeviceA : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(DeviceA::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	DeviceA::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_TestAttribute_A1_read;
	Tango::DevDouble	*attr_TestAttribute_A2_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DeviceA(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DeviceA(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	DeviceA(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~DeviceA() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : DeviceA::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : DeviceA::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute TestAttribute_A1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_TestAttribute_A1(Tango::Attribute &attr);
	virtual void write_TestAttribute_A1(Tango::WAttribute &attr);
	virtual bool is_TestAttribute_A1_allowed(Tango::AttReqType type);
/**
 *	Attribute TestAttribute_A2 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_TestAttribute_A2(Tango::Attribute &attr);
	virtual void write_TestAttribute_A2(Tango::WAttribute &attr);
	virtual bool is_TestAttribute_A2_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : DeviceA::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command GrabImage related method
	 *	Description: 
	 *
	 */
	virtual void grab_image();
	virtual bool is_GrabImage_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : DeviceA::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(DeviceA::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	DeviceA::Additional Method prototypes
};

/*----- PROTECTED REGION ID(DeviceA::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	DeviceA::Additional Classes Definitions

}	//	End of namespace

#endif   //	DeviceA_H
