/*----- PROTECTED REGION ID(DeviceA.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceA.cpp
//
// description : C++ source for the DeviceA class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               DeviceA are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DeviceA.h>
#include <DeviceAClass.h>

/*----- PROTECTED REGION END -----*/	//	DeviceA.cpp

/**
 *  DeviceA class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  GrabImage     |  grab_image
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  TestAttribute_A1  |  Tango::DevDouble	Scalar
//  TestAttribute_A2  |  Tango::DevDouble	Scalar
//================================================================

namespace DeviceA_ns
{
/*----- PROTECTED REGION ID(DeviceA::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	DeviceA::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : DeviceA::DeviceA()
 *	Description : Constructors for a Tango device
 *                implementing the classDeviceA
 */
//--------------------------------------------------------
DeviceA::DeviceA(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(DeviceA::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::constructor_1
}
//--------------------------------------------------------
DeviceA::DeviceA(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(DeviceA::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::constructor_2
}
//--------------------------------------------------------
DeviceA::DeviceA(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(DeviceA::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : DeviceA::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void DeviceA::delete_device()
{
	DEBUG_STREAM << "DeviceA::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceA::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::delete_device
	delete[] attr_TestAttribute_A1_read;
	delete[] attr_TestAttribute_A2_read;
}

//--------------------------------------------------------
/**
 *	Method      : DeviceA::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void DeviceA::init_device()
{
	DEBUG_STREAM << "DeviceA::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceA::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::init_device_before
	
	//	No device property to be read from database
	
	attr_TestAttribute_A1_read = new Tango::DevDouble[1];
	attr_TestAttribute_A2_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(DeviceA::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::init_device
}


//--------------------------------------------------------
/**
 *	Method      : DeviceA::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void DeviceA::always_executed_hook()
{
	DEBUG_STREAM << "DeviceA::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceA::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : DeviceA::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void DeviceA::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "DeviceA::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(DeviceA::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : DeviceA::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void DeviceA::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "DeviceA::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(DeviceA::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute TestAttribute_A1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DeviceA::read_TestAttribute_A1(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DeviceA::read_TestAttribute_A1(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(DeviceA::read_TestAttribute_A1) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_TestAttribute_A1_read);
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::read_TestAttribute_A1
}
//--------------------------------------------------------
/**
 *	Write attribute TestAttribute_A1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DeviceA::write_TestAttribute_A1(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "DeviceA::write_TestAttribute_A1(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(DeviceA::write_TestAttribute_A1) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::write_TestAttribute_A1
}
//--------------------------------------------------------
/**
 *	Read attribute TestAttribute_A2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DeviceA::read_TestAttribute_A2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DeviceA::read_TestAttribute_A2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(DeviceA::read_TestAttribute_A2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_TestAttribute_A2_read);
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::read_TestAttribute_A2
}
//--------------------------------------------------------
/**
 *	Write attribute TestAttribute_A2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DeviceA::write_TestAttribute_A2(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "DeviceA::write_TestAttribute_A2(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(DeviceA::write_TestAttribute_A2) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::write_TestAttribute_A2
}

//--------------------------------------------------------
/**
 *	Method      : DeviceA::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void DeviceA::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(DeviceA::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command GrabImage related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void DeviceA::grab_image()
{
	DEBUG_STREAM << "DeviceA::GrabImage()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceA::grab_image) ENABLED START -----*/
	
	//	Add your own code
    std::cout << "Client called GrabImage()." << std::endl;
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::grab_image
}
//--------------------------------------------------------
/**
 *	Method      : DeviceA::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void DeviceA::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(DeviceA::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	DeviceA::add_dynamic_commands
}

/*----- PROTECTED REGION ID(DeviceA::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	DeviceA::namespace_ending
} //	namespace
